# Copyright 2020 Canonical Ltd.
# See LICENSE file for licensing details.
options:
    container_port:
        type: int
        description: |
          The port to use for the container, which translates to k8s 'containerPort' and 'ReadinessProbe'.

          This setting is required.
        default: 389
